aws_region          = "us-east-1"
project_id          = "cmtr-d8cbjg27"
vpc_name            = "cmtr-d8cbjg27-vpc"
public_subnet_name  = "cmtr-d8cbjg27-public-subnet-1"
security_group_name = "cmtr-d8cbjg27-sg"
